name : Artifact

on : [push]

env :
  ARTIFACT_NAME=Abhishek_artifact

jobs:
  main:
    runs-on : ubuntu-latest
    steps:
      - name : check_artifact
        uses : action/checkout@v1
      - name : upload_Artifact
        uses : action/upload-artifact@v1
        with:
          name : ${{env.ARTIFACT_NAME}}
          path : .
