name: Run_and_create_Artifact

on: [push]

env:
  ARTIFACT_NAME: python_artifact

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: check and test artifact
        uses: actions/checkout@v2
      - run: python hello_world.py
      
      - name: upload_Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: .
