name: Artifact

on: [push]

env:
  ARTIFACT_NAME: Abhishek_artifact

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: check_artifact
        uses: action/checkout@v2
      - name: upload_Artifact
        uses: action/upload-artifact@v2
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: .
